### ISSUE TITLE
[Frongo] Create webpage create webpage for testing Frongo

### ISSUE THREAD

**Issue by Jailander** [strands-project/fremen#28]
We wanted to have have a webpage to test the functionality of Frongo. @marc-hanheide committed to this TG.

**Comment by marc-hanheide** [comment]
Can you add what a query to frongo would look like and paste some example of what it will return (in JSON/YAML)? @Jailander

**Comment by Jailander** [comment]
https://github.com/Jailander/fremen/tree/frongo-2/frongo there is a very short README there I'll improve it in a bit

**Comment by marc-hanheide** [comment]
here's what it could looks like:
![image](https://cloud.githubusercontent.com/assets/1153084/16412443/22f0bc8c-3d24-11e6-830f-562775f1abd2.png)

**Comment by marc-hanheide** [comment]
but your readme doesn't say what a query would look like and what it would return... @Jailander

**Comment by Jailander** [comment]
Oh nice!!! Will push some changes after lunch that will make your life easier, also the service `/frongo/add_model_defs` allows you to send a yaml string with the definitions

**Comment by Jailander** [comment]
oh yes I'm changing the README now, but I'm stuck making some changes in top pred

**Comment by Jailander** [comment]
the service `/frongo/predict_models`: 
```
string model_name
uint32[] epochs
---
uint32[] epochs
float64[] probs
```
does the trick I'll add this in my PR

**Comment by marc-hanheide** [comment]
So, what we need:

- [ ] service to return all available models
- [ ] call to retrieve actual data between two epochs, using same service interface [frongo/PredictState](https://github.com/strands-project/fremen/blob/master/frongo/srv/PredictState.srv), with intervals being defined as pairs in the list, with even being start epoch and odd being end epoch of interal. It returns a list of epoch and values for which data exists.
- [ ] service to retreive entropies.

**Comment by Jailander** [comment]
#31 adds rosservice `/frongo/get_models` and a simple test launch file [this](https://lcas.lincoln.ac.uk/owncloud/index.php/s/z1ZHrFleGfu0rgR) link has mongodumps to test frongo and work with these yaml files: 
[frongo_defs.zip](https://github.com/strands-project/fremen/files/339890/frongo_defs.zip)

**Comment by Jailander** [comment]
#32 has the services for entropy estimation

**Comment by marc-hanheide** [comment]
slowly getting there:

![image](https://cloud.githubusercontent.com/assets/1153084/16471454/b639d844-3e54-11e6-8bbd-446b372f58d2.png)

Still to test with actual data (somehow I didn't get mongo to run properly locally, so I shall try in uni tomorrow rather than wasting my time).

**Comment by marc-hanheide** [comment]
Done: https://lcas.lincoln.ac.uk/owncloud/index.php/s/IAVDwLjMB9oWRj9

I'll test a bit more and check with @Jailander then I'll open the PR.
